### ISSUE TITLE
В методе add() значение переменной balance неверно обновляется

### ISSUE THREAD

**Issue by Anastasi97** [Anastasi97/ForTeamWork#1]
# Описание 
В методе add() значение переменной balance неверно обновляется. Вместо balance = amount необходимо использовать balance += amount.

# Локация дефекта
https://github.com/Anastasi97/ForTeamWork/blob/d638da400a507d0844cf60ae3af1a97b63e25c2b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L70

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Anastasi97/ForTeamWork/blob/d638da400a507d0844cf60ae3af1a97b63e25c2b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Выставить значение переменной initialBalance = 5
3. Выставить значение переменной amount = 3000
4. Запустить программу
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения о балансе в 3005
*Фактический результат:* Вывод сообщения о балансе в 3000

# Тест
https://github.com/Anastasi97/ForTeamWork/blob/64e121dfc2efa4f3115226d1fc34169a2eac73af/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L23

# Скриншот 
![=+](https://github.com/Anastasi97/ForTeamWork/assets/127952654/ebf4392f-c4e5-459c-b392-937e6720cb1d)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2022.3.2
* **Java:** OpenJDK 11

**Comment by Krastist** [comment]
Ошибка в методе исправлена, тесты проходят успешно.

**Comment by Krastist** [comment]
# Описание
Ошибка в методе исправлена, тесты проходят успешно.

# Локация
https://github.com/Anastasi97/ForTeamWork/blob/619350dc547860ab82e982f9fd851714bbece6fe/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L70

# Скриншоты
![add](https://github.com/Anastasi97/ForTeamWork/assets/128929997/85f37648-19e4-4a50-b142-1887d235258c)
