### ISSUE TITLE
В методе pay() некорректно обновляется значение переменной balance

### ISSUE THREAD

**Issue by Anastasi97** [Anastasi97/ForTeamWork#2]
# Описание 
В методе pay() некорректно обновляется значение переменной balance при выполнении условия balance > -creditLimit. Вместо if (balance > -creditLimit) { balance = -amount; необходимо использовать if (balance - amount >= -creditLimit) { balance -= amount;

# Локация дефекта
https://github.com/Anastasi97/ForTeamWork/blob/d638da400a507d0844cf60ae3af1a97b63e25c2b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L47

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Anastasi97/ForTeamWork/blob/d638da400a507d0844cf60ae3af1a97b63e25c2b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Выставить значение переменной initialBalance = 5
3. Выставить значение переменной amount = 3000
4. Выставить значение переменной creditLimit = 5000
5. Запустить программу
6. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения о балансе в -2 995
*Фактический результат:* Вывод сообщения о балансе в -3000

# Тест
https://github.com/Anastasi97/ForTeamWork/blob/64e121dfc2efa4f3115226d1fc34169a2eac73af/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L49

# Скриншот 
![2995](https://github.com/Anastasi97/ForTeamWork/assets/127952654/cd88ed0a-d413-4275-b5c0-9c98deef8fce)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2022.3.2
* **Java:** OpenJDK 11

**Comment by Krastist** [comment]
# Описание
Ошибка в методе исправлена, тесты проходят успешно.

# Локация
https://github.com/Anastasi97/ForTeamWork/blob/619350dc547860ab82e982f9fd851714bbece6fe/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46
https://github.com/Anastasi97/ForTeamWork/blob/619350dc547860ab82e982f9fd851714bbece6fe/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L47

# Скриншоты
![pay](https://github.com/Anastasi97/ForTeamWork/assets/128929997/98e1007a-e715-41e0-b54e-cc458c65ab55)
