### ISSUE TITLE
В методе yearChange() некорректно происходит расчёт процентов.

### ISSUE THREAD

**Issue by Anastasi97** [Anastasi97/ForTeamWork#3]
# Описание 
В методе yearChange() код не учитывает отрицательный баланс счета, т.к. при делении отрицательного значения на положительное, ответ будет отрицательным, а не целым числом. Следует исправить на if (balance < 0) {
            return (int)Math.floor(balance * rate / 100);
        } else {
            return 0;
        }

# Локация дефекта
https://github.com/Anastasi97/ForTeamWork/blob/d638da400a507d0844cf60ae3af1a97b63e25c2b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L84

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Anastasi97/ForTeamWork/blob/d638da400a507d0844cf60ae3af1a97b63e25c2b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Выставить значение переменной initialBalance = 200
3. Выставить значение переменной rate = 15
4. Запустить программу
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения о ставке 0
*Фактический результат:* Вывод сообщения о балансе в 30

# Тест
https://github.com/Anastasi97/ForTeamWork/blob/64e121dfc2efa4f3115226d1fc34169a2eac73af/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L88

# Скриншот 
![000](https://github.com/Anastasi97/ForTeamWork/assets/127952654/e2d410e6-bdbb-47f2-8935-4ffcf8ac94b2)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2022.3.2
* **Java:** OpenJDK 11

**Comment by Krastist** [comment]
# Описание
Ошибка в методе исправлена, тесты проходят успешно.

# Локация
https://github.com/Anastasi97/ForTeamWork/blob/619350dc547860ab82e982f9fd851714bbece6fe/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L84

# Скриншоты
![yearchange](https://github.com/Anastasi97/ForTeamWork/assets/128929997/61fce947-4cfe-463e-9795-d481701da4b7)
![image](https://github.com/Anastasi97/ForTeamWork/assets/128929997/ecd2f29e-1ed6-457b-82c9-db0bfc9eaac7)
