### ISSUE TITLE
Некорректный расчет в методе "pay"

### ISSUE THREAD

**Issue by Krastist** [Anastasi97/ForTeamWork#4]
# Описание
При расчете баланса после покупки, расчет происходит до того как сравнивается баланс и минимальный баланс. 

# Локация дефекта
https://github.com/Anastasi97/ForTeamWork/blob/d5e7afb27fc07bc0179f27f94cb6a2fa0863917e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Anastasi97/ForTeamWork/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса **SavingAccount** с балансом 100, минимальным балансом 10, стоимостью покупки 91
3. Запустить программу
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод значения **100**
*Фактический результат:* Вывод значения **9**

# Тест метода
https://github.com/Anastasi97/ForTeamWork/blob/d5e7afb27fc07bc0179f27f94cb6a2fa0863917e/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L60

# Скриншот
![2023-06-03_16-05-14](https://github.com/Anastasi97/ForTeamWork/assets/128929997/178cd5c8-33c4-459a-9fcc-92000b520c44)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** Open JDK 11

**Comment by Anastasi97** [comment]
## Ошибка в методе Pay исправлена

## Локация 
https://github.com/Anastasi97/ForTeamWork/blob/d638da400a507d0844cf60ae3af1a97b63e25c2b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

##Скриншот
![pay](https://github.com/Anastasi97/ForTeamWork/assets/127952654/e9aab8ab-18d1-4d33-8d3e-4b44e3be1583)
