### ISSUE TITLE
Некорректный расчет в методе "add"

### ISSUE THREAD

**Issue by Krastist** [Anastasi97/ForTeamWork#5]
# Описание
При расчете баланса, после сравнения баланса + сумма пополнения с максимальным балансом, баланс приравнивается к сумму пополнения. 

# Локация дефекта
https://github.com/Anastasi97/ForTeamWork/blob/d5e7afb27fc07bc0179f27f94cb6a2fa0863917e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Anastasi97/ForTeamWork/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса **SavingAccount** с балансом 2.000, максимальным балансом 10.000, суммой пополнения 3.000
3. Запустить программу
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод значения **5.000**
*Фактический результат:* Вывод значения **3.000**

# Тест метода
https://github.com/Anastasi97/ForTeamWork/blob/d5e7afb27fc07bc0179f27f94cb6a2fa0863917e/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

# Скриншот
![2023-06-03_16-14-39](https://github.com/Anastasi97/ForTeamWork/assets/128929997/f0e1e667-23e1-4835-a6f8-aa5342a000b9)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** Open JDK 11

**Comment by Anastasi97** [comment]
## Ошибка в методе Add исправлена

## Локация
https://github.com/Anastasi97/ForTeamWork/blob/d638da400a507d0844cf60ae3af1a97b63e25c2b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72
https://github.com/Anastasi97/ForTeamWork/blob/d638da400a507d0844cf60ae3af1a97b63e25c2b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73

## Скриншот
![add](https://github.com/Anastasi97/ForTeamWork/assets/127952654/401ede9e-4227-455d-81f4-52cc807247d0)
