### ISSUE TITLE
Некорректный расчет в методе "yearChange"

### ISSUE THREAD

**Issue by Krastist** [Anastasi97/ForTeamWork#6]
# Описание
При расчете баланса, в коде нет присвоения формулы к переменной **balance**. 

# Локация дефекта
https://github.com/Anastasi97/ForTeamWork/blob/d5e7afb27fc07bc0179f27f94cb6a2fa0863917e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Anastasi97/ForTeamWork/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса **SavingAccount** с балансом 200, ставкой 15
3. Запустить программу
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод значения **30**
*Фактический результат:* Вывод значения **200**

# Тест метода
https://github.com/Anastasi97/ForTeamWork/blob/d5e7afb27fc07bc0179f27f94cb6a2fa0863917e/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L78

# Скриншот
![2023-06-03_16-19-42](https://github.com/Anastasi97/ForTeamWork/assets/128929997/4d6d92da-dc0d-4e86-9713-ae86de04c3fa)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** Open JDK 11

**Comment by Anastasi97** [comment]
## Ошибка в методе исправлена

## Локация
https://github.com/Anastasi97/ForTeamWork/blob/d638da400a507d0844cf60ae3af1a97b63e25c2b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88

## Скриншот
![111](https://github.com/Anastasi97/ForTeamWork/assets/127952654/5fe1cb53-639b-469e-8c0a-19dc34026a23)
